### PR TITLE
Add imu support and vesc udev enumeration tools (rebase upstream ros2)

### PR DESCRIPTION
**Pull request by anscipione**
- added tool to enumerate vescs based on their uuid (/dev/vesc/XXXX-XXXX-XXXX)
- added support to read imu data

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@anscipione The copyright check failed on at least one of your files. Can you please run `colcon test --packages-select vesc && colcon test-result --verbose` and fix the issues provided?

**Comment by anscipione** [comment]
the checks do not pass because the code on which I have based the rebase lacks the copyright.

in particular it is missing on the new launch file.  it is not code written by me so I would not want to put an incorrect copyright.  can you tell me what kind of copyright to put

**Comment by JWhitleyWork** [comment]
Closing as the branch for this PR no longer exists. @anscipione The formatting issues on the `ros2` branch have been corrected. Please provide a new PR and I'll make sure to get it in this time.

**Comment by anscipione** [comment]
Ok I'll make asap

**Pull request closed without merging**
