### PR TITLE
Add current control to vesc driver

### PR DESCRIPTION
**Pull request by tbalch-tri**
This allows a user to use the throttle command to control the vesc via current (acceleration). The values for the current should fall between [-1, 1]

### CODE REVIEW

**Comment by tbalch-tri** [comment]
There are some tuning adjustments that can be done in the vesc itself and at the hardware level which will make driving with current control much smoother

**Comment by hzheng40** [comment]
Just a couple of lint errors from the ROS1 CI, otherwise looks good to me.

**Comment by tbalch-tri** [comment]
I literally just pushed the changes up to the branch! Sorry it took a bit to get to it. If you want, I can open a new PR with the linter fixes?

**Comment by hzheng40** [comment]
Haha yea, you can open a new PR.

**Pull request merged**
