### PR TITLE
Fix compatibility with ros 2 humble.

### PR DESCRIPTION
**Pull request by ValerioMagnago**
Unfortunately, I didn't find a better solution to support both ros2 foxy and humble.

Do you have any suggestions?
 
It would be nice to wait https://github.com/f1tenth/vesc/pull/32 so the workflow will test this against ros2 humble.

### CODE REVIEW

**Comment by sisaha9** [comment]
To avoid having a default value you can also do `declare_parameter<type>("param_name");`

**Comment by ValerioMagnago** [comment]
@sisaha9  I tried but this was not compiling on foxy and I wasn't sure if we can drop the compatibility with foxy from here.

**Comment by JWhitleyWork** [comment]
Please rebase to pick up changes from #32.

**Comment by ValerioMagnago** [comment]
Fixing the linting for ros humble breaks the tests for foxy.
How do we proceed here? Since the linting is the only test in this package, we do not need to run the test with both ros distro, so disabling the test for foxy might also be an option.

**Comment by JWhitleyWork** [comment]
Please remove the foxy job on this branch. I've created a `foxy` branch from this branch that can be used for future Foxy development. This branch can target Humble going forward.

**Comment by ValerioMagnago** [comment]
> To avoid having a default value you can also do declare_parameter<type>("param_name");

@sisaha9  I implemented your suggestion since the support of foxy is not required :)

**Comment by ValerioMagnago** [comment]
@JWhitleyWork  is there anything I can do here to help?

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
